In [1]:
import torch
x=torch.empty(2) # uninitialized(random) values in the vector
print(x)


tensor([0., 0.])


In [3]:
torch.empty(3)


tensor([0., 0., 0.])

In [5]:
torch.empty(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.rand(2,3)

tensor([[0.8510, 0.7914, 0.7545],
        [0.7415, 0.9757, 0.2595]])

In [7]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
print(torch.ones(2,3,dtype=torch.float16))


tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)


In [9]:
print(x.dtype)

torch.float32


In [12]:
print(x.size())

torch.Size([2])


In [15]:
y=torch.tensor([2.5,3.6])
y

tensor([2.5000, 3.6000])

In [18]:
#operators work more or less like numpy
x=torch.tensor([1,4])
y=torch.tensor([2,3])
print(x,' ',y)
print(x+y,' ',torch.add(x,y))
print(x-y,' ',torch.sub(x,y))
print(x*y,' ',torch.mul(x,y))
print(x/y,' ',torch.div(x,y))
print(x.dot(y))

tensor([1, 4])   tensor([2, 3])
tensor([3, 7])   tensor([3, 7])
tensor([-1,  1])   tensor([-1,  1])
tensor([ 2, 12])   tensor([ 2, 12])
tensor([0.5000, 1.3333])   tensor([0.5000, 1.3333])
tensor(14)


In [19]:
#inplace operations- same operations but with an underscore
y.add_(x)
print(y)

tensor([3, 7])


In [20]:
#slicing like numpy arrays is also valid
z=torch.rand(5,3)
print(z)
print(z[:,1:])

tensor([[0.6411, 0.0725, 0.1019],
        [0.8351, 0.8413, 0.7158],
        [0.8776, 0.6073, 0.9281],
        [0.3597, 0.1900, 0.8691],
        [0.4933, 0.4353, 0.4978]])
tensor([[0.0725, 0.1019],
        [0.8413, 0.7158],
        [0.6073, 0.9281],
        [0.1900, 0.8691],
        [0.4353, 0.4978]])


In [21]:
#.item() method
#we can only use this when we have a 1x1 tenaor
print(z[2,2].item())

0.9280954599380493


In [ ]:
#reshaping
x=torch.randint(low=0,high=6,size=(4,4)) #high value is exclusive
print(x)
y=x.view(-1) #calc dimension yourself
print(y)

tensor([[2, 3, 3, 5],
        [3, 0, 1, 4],
        [3, 2, 2, 5],
        [1, 4, 1, 0]])
tensor([2, 3, 3, 5, 3, 0, 1, 4, 3, 2, 2, 5, 1, 4, 1, 0])


In [27]:
#y is a shallow copy of x, changes in y and x affect each other
y[0]=3
print(y)
print(x)

tensor([3, 3, 3, 5, 3, 0, 1, 4, 3, 2, 2, 5, 1, 4, 1, 0])
tensor([[3, 3, 3, 5],
        [3, 0, 1, 4],
        [3, 2, 2, 5],
        [1, 4, 1, 0]])


In [29]:
z=x.view(-1,8)
print(z)
print(z.size())
print(z.shape)
print(z.numel()) #total no. of elements, like size para in numpy

tensor([[3, 3, 3, 5, 3, 0, 1, 4],
        [3, 2, 2, 5, 1, 4, 1, 0]])
torch.Size([2, 8])
torch.Size([2, 8])
16


If you have GPU available and want to perform faster operations using it-
you have to move the tensor to the gpu
but note that, a gpu tensor cannot be converted to numpy array, to do that it has to be brought back to cpu


In [1]:
import torch 
import numpy as np
if torch.cuda.is_available():
    device=torch.device("cuda")
    x=torch.ones(5,device=device)
    y=torch.ones(5)
    y=y.to(device)
    z=x+y#much faster
    z=z.to("cpu") #now numpy can handle it
    print(z)

In [31]:
#requires_grad
x=torch.ones(5,requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
